// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpyzxtcmgcwkuzuuoehc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNweXp4dGNtZ2N3a3V6dXVvZWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjQ5MTcsImV4cCI6MjA1ODg0MDkxN30.AiKc9OOEDT8g7X261f9l2JAfhSMr52prXJtev98tmu8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);